(function(){const c=window.PORTFOLIO_CONFIG;if(!c)return;const skills=document.getElementById("skills-grid"),projects=document.getElementById("projects-grid");const tag=t=>{const s=document.createElement("span");s.className="tag";s.textContent=t;return s};Object.entries(c.skills).forEach(([name,items])=>{const el=document.createElement("article");el.className="skill";const h=document.createElement("h3");h.textContent=name;const tags=document.createElement("div");tags.className="tags";items.forEach(t=>tags.append(tag(t)));el.append(h,tags);skills.append(el)});c.projects.forEach((p,i)=>{const card=document.createElement("article");card.className="project";const index=document.createElement("div");index.className="idx";index.textContent="SELECTED WORK / 0"+(i+1);const h=document.createElement("h3");h.textContent=p.name;const desc=document.createElement("p");desc.textContent=p.description;const tags=document.createElement("div");tags.className="tags";p.technologies.forEach(t=>tags.append(tag(t)));const links=document.createElement("div");links.className="projectlinks";for(const [key,label] of [["github","Repository ↗"],["demo","Live demo ↗"]]){if(p[key]){const a=document.createElement("a");a.href=p[key];a.textContent=label;a.target="_blank";a.rel="noopener noreferrer";links.append(a)}}if(p.repositoryNote){const note=document.createElement("span");note.textContent=p.repositoryNote;note.className="muted";links.append(note)}card.append(index,h,desc,tags,links);projects.append(card)})})();
(function(){
  const c=window.PORTFOLIO_CONFIG && window.PORTFOLIO_CONFIG.personal;if(!c)return;
  const intro=document.getElementById("personal-intro");
  if(intro && typeof c.intro==="string" && c.intro.trim()){intro.textContent=c.intro;intro.classList.remove("personal-placeholder")}
  const now=document.getElementById("now-list");
  if(now){(c.now||[]).forEach(item=>{const li=document.createElement("li"),date=document.createElement("span"),text=document.createElement("span");date.className="now-date";date.textContent=item.date;text.textContent=item.text;li.append(date,text);now.append(li)});if(!now.children.length){const li=document.createElement("li");li.textContent="No current updates yet.";now.append(li)}}
  const interests=document.getElementById("personal-interests");
  if(interests){(c.interests||[]).forEach(item=>{const span=document.createElement("span");span.className="tag";span.textContent=item;interests.append(span)})}
  const notes=document.getElementById("personal-notes");
  if(notes && c.notes && c.notes.length){notes.replaceChildren();c.notes.forEach(note=>{const article=document.createElement("article");const h=document.createElement("h3"),p=document.createElement("p");h.textContent=note.title;p.textContent=note.text;article.append(h,p);notes.append(article)})}
})();
